Repository amosproj/amos2023ws06-sales-lead-qualifier, pull requests merged in 2023-10, with the labels that each got.

#14 Feature/team logo
  Deliverables/sprint-01/team-logo.png
  README.md
Labels: organization

#16 Upload planning document PDF
  Deliverables/sprint-01/Dummy.md
  Deliverables/sprint-01/planning-document.pdf
Labels: organization

#13 Added technology and Repository tools. Issue: #3.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  .pre-commit-config.yaml
  Deliverables/README.md
  Deliverables/sprint-01/planning-document.pdf.license
  Deliverables/sprint-01/team-logo.png.license
  Documentation/README.md
  LICENSES/MIT.txt
  Pipfile
  README.md
Labels: documentation

#15 Add documentation regarding the software architecture
  Documentation/Architecture.md
  Documentation/Media/component-diagram.svg
  Documentation/Media/sequence-diagram.svg
Labels: documentation

#38 Feature/9 initial cicd pipeline
  .github/workflows/python-app.yml
  Documentation/Media/BDC_Features.drawio
  Documentation/Media/BDC_Features.drawio.license
  Pipfile
  src/test_dummy.py
Labels: infrastructure
