Repository amosproj/amos2023ws06-sales-lead-qualifier, pull requests merged in 2023-12, with the labels that each got.

#157 added research documentation about twitter
  Documentation/Twiiter-API-Limitation.md
Labels: research

#158 Refactoring facebook api
  src/bdc/steps/social_media_api.py
Labels: refactoring

#160 upload sprint-07 imp-squared-backlog.jpg
  Deliverables/sprint-07/imp-squared-backlog.jpg
  Deliverables/sprint-07/imp-squared-backlog.jpg.license
Labels: organization
