Repository amosproj/amos2023ws06-sales-lead-qualifier, pull requests merged in 2024-02, with the labels that each got.

#230 Refactor/remove unused code
  .env.template
  Dockerfile
  Documentation/ideas.md
  Pipfile
  Pipfile.lock
  build_app.sh
  deprecated/controller/Controller.py
  deprecated/controller/messenger.py
  deprecated/steps/social_media_api.py
  docker-compose.yml
  run_app.sh
  scripts/create_geojson.py
  scripts/model_testing/ml_model.py
  scripts/model_testing/nn_model.py
  scripts/model_testing/requirements.txt
  scripts/model_testing/sagemaker_training.py
  scripts/report.py
  src/bdc/__init__.py
  src/bdc/data_collector.py
  src/bdc/pipeline.py
  src/bdc/steps/__init__.py
  src/database/__init__.py
  src/database/database_dummy.py
  src/database/db_connection.py
  src/database/models.py
  src/database/parsers.py
  src/demo/__init__.py
  src/demo/console_utils.py
  src/demo/demos.py
  src/demo/pipeline_configs/config_sprint09_release.json
  src/demo/pipeline_configs/config_template
  src/demo/pipeline_configs/run_all_steps.json
  src/demo/pipeline_utils.py
  src/evp/data_processing.py
  src/main.py
  src/models/.gitkeep
  tests/conftest.py
  tests/mock_components.py
  tests/test_console_utils.py
  tests/test_leadparser.py
Labels: refactoring

#236 Prediction runs both locally and via S3
  .gitignore
  Pipfile.lock
  src/data/models/.gitkeep
  src/data/preprocessed_data_files/.gitkeep
  src/database/leads/local_repository.py
  src/database/leads/s3_repository.py
  src/demo/demos.py
  src/preprocessing/preprocessing.py
Labels: bugfix

#240 Feature/229 more test cases
  .gitignore
  tests/__init__.py
  tests/steps/test_analyze_emails.py
  tests/steps/test_hash_generator.py
  tests/steps/test_preprocess_phonenumbers.py
  tests/test_pipeline_utils.py
Labels: feature
